### 書籍登録
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "よくわかるJavaScript",
  "price": 2500,
  "status": "UNPUBLISHED",
  "authors": [
    {
      "name": "山田太郎",
      "birthDate": "1985-01-01"
    },
    {
      "name": "佐藤花子",
      "birthDate": "1990-05-15"
    }
  ]
}

### 書籍更新
PUT http://localhost:8080/api/books/1
Content-Type: application/json

{
  "title": "よくわかるJavaScript",
  "price": 2500,
  "status": "PUBLISHED",
  "authors": [
    {
      "name": "山田太郎",
      "birthDate": "1985-01-01"
    }
  ]
}

### 著者に紐づく書籍一覧取得
GET http://localhost:8080/api/books/authors/1